# Generated by Django 2.2.24 on 2025-02-10 16:18

from django.db import migrations


def update_new_building(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    
    Flat.objects.filter(construction_year__isnull=False).update(
        new_building=True
    )
    
    Flat.objects.filter(construction_year__lte=2015).update(
        new_building=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20250206_2159'),
    ]

    operations = [
        migrations.RunPython(update_new_building),
    ]
