# Generated by Django 2.2.24 on 2025-01-13 12:35

from django.db import migrations


def copy_flats_to_new_flat(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        if flat.construction_year >= 2015:
            flat.new_building = True
        else:
            flat.new_building = False
        flat.save()
          
class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20250113_1602'),
    ]

    operations = [
        migrations.RunPython(copy_flats_to_new_flat),
    ]
    
