# Generated by Django 2.2.24 on 2025-01-13 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20250113_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('construction_year', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Год постройки здания')),
                ('new_building', models.BooleanField(db_index=True, null=True, verbose_name='Новое здание')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=200, verbose_name='Кто пожаловался')),
                ('text_complaint', models.CharField(max_length=200, verbose_name='Текст жалобы')),
                ('flat_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.Flat', verbose_name='Квартира, на которую пожаловались')),
            ],
        ),
    ]
