# Generated by Django 2.2.24 on 2025-01-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_complaint_new_flat'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Имя пользователя')),
                ('password', models.CharField(max_length=200, verbose_name='Пароль')),
                ('email', models.EmailField(max_length=200, verbose_name='Почта')),
                ('firs_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=200, verbose_name='Фамилия')),
            ],
        ),
        migrations.AlterField(
            model_name='complaint',
            name='text_complaint',
            field=models.TextField(max_length=200, verbose_name='Текст жалобы'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.User', verbose_name='Кто пожаловался'),
        ),
    ]
