# Generated by Django 5.1.6 on 2025-02-11 16:30

from django.db import migrations
import phonenumbers


def normalize_phone_numbers(apps, schema_editor):
    Flat = apps.get_model("property", "Flat")
    
    for flat in Flat.objects.all():
        if flat.owners_phonenumber:
            try:
                parsed_number = phonenumbers.parse(flat.owners_phonenumber, "RU")
                if phonenumbers.is_valid_number(parsed_number):
                    flat.owner_pure_phone = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
                else:
                    flat.owner_pure_phone = None
                flat.save(update_fields=["owner_pure_phone"])
            except:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone_alter_flat_has_balcony'),
    ]

    operations = [
        migrations.RunPython(normalize_phone_numbers),
    ]
