# Generated by Django 5.1.4 on 2025-01-27 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0014_alter_owner_name_alter_owner_phonenumber'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='flat_complaint',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='text_complaint',
        ),
        migrations.AddField(
            model_name='complaint',
            name='flat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flat_complaints', to='property.flat', verbose_name='Квартира, на которую пожаловались'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст жалобы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Кто пожаловался'),
        ),
    ]
