# Generated by Django 5.1.4 on 2025-01-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_remove_complaint_flat_complaint_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
    ]
