# Generated by Django 5.1.4 on 2025-01-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0017_alter_complaint_flat_alter_complaint_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New_Flat',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
    ]
