# Generated by Django 5.1.4 on 2025-02-01 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_alter_complaint_flat_alter_complaint_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owned_flats',
        ),
        migrations.AddField(
            model_name='owner',
            name='property',
            field=models.ManyToManyField(blank=True, related_name='property', to='property.flat', verbose_name='Квартиры в собственности'),
        ),
    ]
