# Generated by Django 5.1.4 on 2025-02-01 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_remove_owner_owned_flats_owner_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
    ]
